Module("TeamMenu.Enums")


LINE_MODE = {}
LINE_MODE.INNER = 1
LINE_MODE.OUTER = 2
LINE_MODE.BOTH = 3


RELATIONSHIP_TYPE = {}
RELATIONSHIP_TYPE.UNKNOWN = 1
RELATIONSHIP_TYPE.ENEMY = 2
RELATIONSHIP_TYPE.FRIEND = 3


ICON_ALIGN = {}
ICON_ALIGN.LEFT = 1
ICON_ALIGN.BEFORE_TEXT = 2
ICON_ALIGN.AFTER_TEXT = 3
ICON_ALIGN.RIGHT = 4


SIDEBAR_ALIGN = {}
SIDEBAR_ALIGN.LEFT = 1
SIDEBAR_ALIGN.RIGHT = 2