uratrecom.autoreport.title=Угода користувача про використання
uratrecom.autoreport.description=Дана модифікація використовує систему автозвітів про помилки.\nДля використовування даної системи потрібен ваш дозвіл на збір наступних даних:\n- Режим гри.\n- Ввімкнені модифікації.\n- Помилки модификації.
uratrecom.autoreport.agree=Прийняти
uratrecom.autoreport.disagree=Відмовитися