uratrecom.autoreport.title=Пользовательское соглашение об использовании
uratrecom.autoreport.description=Данная модификация использует систему автоотчетов об ошибках.\nДля использования данной системы нужно ваше разрешение на сбор следующих данных:\n- Режим игры.\n- Включенные модификации.\n- Ошибки модификации.
uratrecom.autoreport.agree=Принять
uratrecom.autoreport.disagree=Отказаться