team_menu.hud.friend=Friend
team_menu.hud.unknown=Unknown
team_menu.hud.enemy=Enemy
team_menu.hud.no_team=No team

team_menu.gui.tab.teams=Teams
team_menu.gui.tab.my_team=My team
team_menu.gui.tab.create_team=Create team
team_menu.gui.tab.settings=Settings
team_menu.gui.refresh=Refresh
team_menu.gui.join=Join
team_menu.gui.leave=Leave

team_menu.convars.hud_show_entity_relationship.description=Show realtionship of an entity