# ------------ Hud ------------
team_menu.hud.friend=Friend
team_menu.hud.unknown=Unknown
team_menu.hud.enemy=Enemy
team_menu.hud.no_team=No team
# ------------ Gui ------------
team_menu.gui.tab_teams=Teams
team_menu.gui.tab_my_team=My team
team_menu.gui.tab_create_team=Create team
team_menu.gui.tab_settings=Settings
team_menu.gui.refresh=Refresh
team_menu.gui.join=Join
team_menu.gui.leave=Leave