uratrecom.autoreport.title=Usage agreement 
uratrecom.autoreport.description=This addon uses a system of automatic error reporting. To use this system, need your permission to collect the following data:\n- Gamemode.\n- Enabled addons.\n- Handle addons errors.
uratrecom.autoreport.agree=Agree
uratrecom.autoreport.disagree=Disagree